In [1]:
3+7

10

In [3]:
3+7

10

In [5]:
import pandas as pd

In [6]:
warehouse_reporting = pd.read_csv("data/warehousing-reporting.csv")

In [7]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [9]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    object
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: int64(3), object(8)
memory usage: 21.2+ KB

In [10]:
warehouse_reporting["COST PER ITEM"] =warehouse_reporting["COST PER ITEM"].str.replace("$", "")
warehouse_reporting["COST PER ITEM"] =warehouse_reporting["COST PER ITEM"].str.replace(",", "")
warehouse_reporting["COST PER ITEM"] =warehouse_reporting["COST PER ITEM"].astype("float")

C:\Users\MOR'SH~1\AppData\Local\Temp/ipykernel_8800/4244192562.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  warehouse_reporting["COST PER ITEM"] =warehouse_reporting["COST PER ITEM"].str.replace("$", "")

In [11]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",18.91,200,"$3,782.00",50,250
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,7.17,100,$717.00,50,150
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",7.25,45,$326.25,50,95
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",8.85,25,$221.25,50,75
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,12.12,200,"$2,424.00",50,250

In [2]:
warehouse_reporting["DATE OF THE LAST ORDER"]

NameError: name 'warehouse_reporting' is not defined

In [20]:
import pandas as pd
warehouse_reporting = pd.read_csv("warehousing-reporting.csv")
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [21]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    object
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: int64(3), object(8)
memory usage: 21.2+ KB

In [22]:
warehouse_reporting.dtypes

REORDER (auto-fill)      object
ITEM NO.                 object
DATE OF LAST ORDER       object
ITEM NAME                object
VENDOR                   object
STOCK LOCATION           object
COST PER ITEM            object
STOCK QUANTITY            int64
TOTAL VALUE              object
REORDER LEVEL             int64
ITEM REORDER QUANTITY     int64
dtype: object

In [25]:
sma_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")
sma_data.shape
sma_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   land_area       99 non-null     int64
 1   percent_city    99 non-null     float64
 2   percent_senior  99 non-null     float64
 3   physicians      99 non-null     int64
 4   hospital_beds   99 non-null     int64
 5   graduates       99 non-null     float64
 6   work_force      99 non-null     float64
 7   income          99 non-null     int64
 8   region          99 non-null     int64
 9   crime_rate      99 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 7.9 KB

In [26]:
sma_data.head()

,land_area,percent_city,percent_senior,physicians,hospital_beds,graduates,work_force,income,region,crime_rate
0,1384,78.1,12.3,25627,69678,50.1,4083.9,72100,1,75.55
1,3719,43.9,9.4,13326,43292,53.9,3305.9,54542,2,56.03
2,3553,37.4,10.7,9724,33731,50.6,2066.3,33216,1,41.32
3,3916,29.9,8.8,6402,24167,52.2,1966.7,32906,2,67.38
4,2480,31.5,10.5,8502,16751,66.1,1514.5,26573,4,80.19

In [41]:
sma_data.iloc[0:4, 4]

0    69678
1    43292
2    33731
3    24167
Name: hospital_beds, dtype: int64

In [1]:
import pandas as pd

In [2]:
warehouse_reporting = pd.read_csv("warehousing-reporting.csv")
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [20]:
warehouse_reporting["DATE OF LAST ORDER"] = pd.datetime9 = (warehouse_reporting["DATE OF LAST ORDER"])

In [21]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    datetime64[ns]
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(7)
memory usage: 21.2+ KB

In [11]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [3]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    object
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: int64(3), object(8)
memory usage: 21.2+ KB

In [4]:
warehouse_reporting["DATE OF LAST ORDER"] =warehouse_reporting["DATE OF LAST ORDER"].astype("datetime64[ns]")

In [6]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [8]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    datetime64[ns]
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(7)
memory usage: 21.2+ KB

In [1]:
import pandas as pd

In [2]:
warehouse_reporting = pd.read_csv("warehousing-reporting.csv")

In [3]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [4]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    object
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: int64(3), object(8)
memory usage: 21.2+ KB

In [6]:
warehouse_reporting ["DATE OF LAST ORDER"] = warehouse_reporting["DATE OF LAST ORDER"].astype("datetime64[ns]")

In [7]:
warehouse_reporting.head()

,REORDER (auto-fill),ITEM NO.,DATE OF LAST ORDER,ITEM NAME,VENDOR,STOCK LOCATION,COST PER ITEM,STOCK QUANTITY,TOTAL VALUE,REORDER LEVEL,ITEM REORDER QUANTITY
0,OK,A121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250
1,OK,B121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150
2,REORDER,C121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95
3,REORDER,D121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75
4,OK,E121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250

In [10]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    datetime64[ns]
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    object
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(7)
memory usage: 21.2+ KB

In [13]:
warehouse_reporting["TOTAL VALUE"].head()

0    $3,782.00
1      $717.00
2      $326.25
3      $221.25
4    $2,424.00
Name: TOTAL VALUE, dtype: object

In [18]:
warehouse_reporting["TOTAL VALUE"] = warehouse_reporting["TOTAL VALUE"].str.replace("$","")
warehouse_reporting["TOTAL VALUE"] = warehouse_reporting["TOTAL VALUE"].str.replace(",","")
warehouse_reporting["TOTAL VALUE"] = warehouse_reporting["TOTAL VALUE"].astype("float")

C:\Users\MOR'SH~1\AppData\Local\Temp/ipykernel_240/1266703022.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  warehouse_reporting["TOTAL VALUE"] = warehouse_reporting["TOTAL VALUE"].str.replace("$","")

In [19]:
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   REORDER (auto-fill)    245 non-null    object
 1   ITEM NO.               245 non-null    object
 2   DATE OF LAST ORDER     245 non-null    datetime64[ns]
 3   ITEM NAME              245 non-null    object
 4   VENDOR                 245 non-null    object
 5   STOCK LOCATION         245 non-null    object
 6   COST PER ITEM          245 non-null    object
 7   STOCK QUANTITY         245 non-null    int64
 8   TOTAL VALUE            245 non-null    float64
 9   REORDER LEVEL          245 non-null    int64
 10  ITEM REORDER QUANTITY  245 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 21.2+ KB

In [20]:
warehouse_reporting["TOTAL VALUE"].head()

0    3782.00
1     717.00
2     326.25
3     221.25
4    2424.00
Name: TOTAL VALUE, dtype: float64

In [37]:
warehouse_reporting["TOTAL VALUE"].head()

0    3782.00
1     717.00
2     326.25
3     221.25
4    2424.00
Name: TOTAL VALUE, dtype: float64

In [45]:
import pandas as pd

In [48]:
warehouse_reporting = pd.read_csv("warehousing-reporting.csv")

In [49]:
warehouse_reporting.head()

,reorder_(auto-fill),item_no,date_of_last_order,item_name,vendor,stock_location,cost_per_item,stock_quantity,total_value,reorder_level,item_reorder_quantity,Unnamed: 11
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250,NaN
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150,NaN
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95,NaN
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75,NaN
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250,NaN

In [55]:
warehouse_reporting["new_column"] = warehouse_reporting['stock_quantity'] < warehouse_reporting['reorder_level']
warehouse_reporting.head()

,reorder_(auto-fill),item_no,date_of_last_order,item_name,vendor,stock_location,cost_per_item,stock_quantity,total_value,reorder_level,item_reorder_quantity,Unnamed: 11,new_column
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250,NaN,False
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150,NaN,False
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95,NaN,True
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75,NaN,True
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250,NaN,False