In [ ]:
# Convert "DATE OF LAST ORDER" to a datetime type. (maybe lookup astype(datetime))
# Convert "TOTAL VALUE" to a float.
# Add a column which calculates the "Reorder Status" from the "STOCK QUANTITY" and "REORDER LEVEL" columns. 
# Split the "STOCK LOCATION" column so "Store Room A" and "Shelf 2" are in different columns. 
# Try and repeat for the shipments csv.

In [25]:
# import pandas
import pandas as pd

In [28]:
# Read csv
warehouse_reporting = pd.read_csv("warehousing-reporting.csv")
warehouse_reporting.head()

,reorder_(auto-fill),item_no,date_of_last_order,item_name,vendor,stock_location,cost_per_item,stock_quantity,total_value,reorder_level,item_reorder_quantity,Unnamed: 11
0,OK,A121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,"$3,782.00",50,250,NaN
1,OK,B121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,$717.00,50,150,NaN
2,REORDER,C121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,$326.25,50,95,NaN
3,REORDER,D121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,$221.25,50,75,NaN
4,OK,E121,20/05/2021,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,"$2,424.00",50,250,NaN

In [29]:
# Check csv information
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   reorder_(auto-fill)    245 non-null    object
 1   item_no                245 non-null    object
 2   date_of_last_order     245 non-null    object
 3   item_name              245 non-null    object
 4   vendor                 245 non-null    object
 5   stock_location         245 non-null    object
 6   cost_per_item          245 non-null    object
 7   stock_quantity         245 non-null    int64
 8   total_value            245 non-null    object
 9   reorder_level          245 non-null    int64
 10  item_reorder_quantity  245 non-null    int64
 11  Unnamed: 11            0 non-null      float64
dtypes: float64(1), int64(3), object(8)
memory usage: 23.1+ KB

In [31]:
# Convert "DATE OF LAST ORDER" to a datetime type. (maybe lookup astype(datetime))
warehouse_reporting["date_of_last_order"] = warehouse_reporting["date_of_last_order"].astype("datetime64[ns]")
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   reorder_(auto-fill)    245 non-null    object
 1   item_no                245 non-null    object
 2   date_of_last_order     245 non-null    datetime64[ns]
 3   item_name              245 non-null    object
 4   vendor                 245 non-null    object
 5   stock_location         245 non-null    object
 6   cost_per_item          245 non-null    object
 7   stock_quantity         245 non-null    int64
 8   total_value            245 non-null    object
 9   reorder_level          245 non-null    int64
 10  item_reorder_quantity  245 non-null    int64
 11  Unnamed: 11            0 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 23.1+ KB

In [32]:
# Convert "TOTAL VALUE" to a float.
warehouse_reporting["total_value"] = warehouse_reporting["total_value"].str.replace("$","")
warehouse_reporting["total_value"] = warehouse_reporting["total_value"].str.replace(",","")
warehouse_reporting["total_value"] = warehouse_reporting["total_value"].astype("float")
warehouse_reporting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   reorder_(auto-fill)    245 non-null    object
 1   item_no                245 non-null    object
 2   date_of_last_order     245 non-null    datetime64[ns]
 3   item_name              245 non-null    object
 4   vendor                 245 non-null    object
 5   stock_location         245 non-null    object
 6   cost_per_item          245 non-null    object
 7   stock_quantity         245 non-null    int64
 8   total_value            245 non-null    float64
 9   reorder_level          245 non-null    int64
 10  item_reorder_quantity  245 non-null    int64
 11  Unnamed: 11            0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 23.1+ KB

C:\Users\MOR'SH~1\AppData\Local\Temp/ipykernel_4980/2146608882.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  warehouse_reporting["total_value"] = warehouse_reporting["total_value"].str.replace("$","")

In [55]:
# Add a column which calculates the "Reorder Status" from the "STOCK QUANTITY" and "REORDER LEVEL" columns. 
warehouse_reporting["reorder_status_new"] = warehouse_reporting["stock_quantity"] < warehouse_reporting["reorder_level"]
warehouse_reporting.head()

,reorder_(auto-fill),item_no,date_of_last_order,item_name,vendor,stock_location,cost_per_item,stock_quantity,total_value,reorder_level,item_reorder_quantity,Unnamed: 11,Reorder Status New,stock_location_1,stock_location_2,reorder_status_new
0,OK,A121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,3782.00,50,250,NaN,False,Store Room A,Shelf 2,False
1,OK,B121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,717.00,50,150,NaN,False,Outdoor Pallet,None,False
2,REORDER,C121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,326.25,50,95,NaN,True,Basement,Shelf 4,True
3,REORDER,D121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,221.25,50,75,NaN,True,Store Room A,Shelf 2,True
4,OK,E121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,2424.00,50,250,NaN,False,Outdoor Pallet,None,False

In [58]:
warehouse_reporting[["reorder_(auto-fill)", "reorder_status_new"]].value_counts()

reorder_(auto-fill)  reorder_status_new
OK                   False                 200
REORDER              True                   45
dtype: int64

In [54]:
# Split the "STOCK LOCATION" column so "Store Room A" and "Shelf 2" are in different columns. 
warehouse_reporting[["stock_location_1", "stock_location_2"]] = warehouse_reporting["stock_location"].str.split(',', expand=True)
warehouse_reporting.head()

,reorder_(auto-fill),item_no,date_of_last_order,item_name,vendor,stock_location,cost_per_item,stock_quantity,total_value,reorder_level,item_reorder_quantity,Unnamed: 11,Reorder Status New,stock_location_1,stock_location_2
0,OK,A121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$18.91,200,3782.00,50,250,NaN,False,Store Room A,Shelf 2
1,OK,B121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$7.17,100,717.00,50,150,NaN,False,Outdoor Pallet,None
2,REORDER,C121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Basement, Shelf 4",$7.25,45,326.25,50,95,NaN,True,Basement,Shelf 4
3,REORDER,D121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.","Store Room A, Shelf 2",$8.85,25,221.25,50,75,NaN,True,Store Room A,Shelf 2
4,OK,E121,2021-05-20,COOLANT RUBBER HOSES,"China Grand Automotive Services Group Co., Ltd.",Outdoor Pallet,$12.12,200,2424.00,50,250,NaN,False,Outdoor Pallet,None